"""empty message

Revision ID: 98181bd1dd86
Revises: e690ecf02cf3
Create Date: 2023-08-28 22:00:02.025900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98181bd1dd86'
down_revision = 'e690ecf02cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###
